export default [
  {
    id: 1,
    title: "Breaking Bad",
    type: "TV Series",
    releaseYear: 2008,
    poster: {
      src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKDpXSjbEBTBIPqNaOfiwk_VPfi6I6-AVklqfGlONWmXtxt3uK",
      alt: "Breaking Bad Poster",
    },
    rating: {
      imdb: 9.5,
      rottenTomatoes: 96,
    },
    genre: ["Crime", "Drama", "Thriller"],
    creator: "Vince Gilligan",
    mainCast: ["Bryan Cranston", "Aaron Paul", "Anna Gunn"],
    seasons: 5,
    episodes: 62,
    streamingOn: ["Netflix", "AMC+"],
    awards: ["16 Primetime Emmy Awards", "2 Golden Globes", "2 Peabody Awards"],
    description:
      "A high school chemistry teacher turned methamphetamine manufacturer partners with a former student to secure his family's financial future as he battles terminal lung cancer.",
    isTopRated: true,
    hasHDContent: true,
  },
  {
    id: 2,
    title: "The Mandalorian",
    type: "TV Series",
    releaseYear: 2019,
    poster: {
      src: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQrnZpOro9MsdCe5GazZKMd_VfpwVr3kBA0G8Nz6tKcRllgd0kX",
      alt: "The Mandalorian Poster",
    },
    rating: {
      imdb: 8.7,
      rottenTomatoes: 93,
    },
    genre: ["Action", "Adventure", "Fantasy"],
    creator: "Jon Favreau",
    mainCast: ["Pedro Pascal", "Carl Weathers", "Giancarlo Esposito"],
    seasons: 3,
    episodes: 24,
    streamingOn: ["Disney+"],
    awards: [
      "14 Primetime Emmy Awards",
      "Visual Effects Society Awards",
      "Art Directors Guild Award",
    ],
    description:
      "The travels of a lone bounty hunter in the outer reaches of the galaxy, far from the authority of the New Republic.",
    isTopRated: true,
    hasHDContent: true,
  },
  {
    id: 3,
    title: "Stranger Things",
    type: "TV Series",
    releaseYear: 2016,
    poster: {
      src: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSsJyOfdEt7I5W1j_UcsQ_EqHBacu5GlFIOs_UnTsSsFxM5eUgEsJcVnz63LCc2H46KP3Jo",
      alt: "Stranger Things Poster",
    },
    rating: {
      imdb: 8.7,
      rottenTomatoes: 92,
    },
    genre: ["Drama", "Fantasy", "Horror"],
    creator: "The Duffer Brothers",
    mainCast: ["Millie Bobby Brown", "Finn Wolfhard", "Winona Ryder"],
    seasons: 4,
    episodes: 34,
    streamingOn: ["Netflix"],
    awards: [
      "7 Emmy Awards",
      "Screen Actors Guild Award",
      "People's Choice Award",
    ],
    description:
      "When a young boy disappears, his mother, a police chief, and his friends must confront terrifying supernatural forces in order to get him back.",
    isTopRated: true,
    hasHDContent: true,
  },
  {
    id: 4,
    title: "House of the Dragon",
    type: "TV Series",
    releaseYear: 2022,
    poster: {
      src: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcR3ss46_Yje-DijO6HOPfsuWTVTyxzZNLCx14UF7YlpPwgj6SEW",
      alt: "House of the Dragon Poster",
    },
    rating: {
      imdb: 8.5,
      rottenTomatoes: 93,
    },
    genre: ["Action", "Adventure", "Drama"],
    creator: "Ryan Condal",
    mainCast: ["Matt Smith", "Emma D'Arcy", "Paddy Considine"],
    seasons: 1,
    episodes: 10,
    streamingOn: ["HBO Max"],
    awards: ["Golden Globe Award", "Critics Choice Award"],
    description:
      "The story of the House Targaryen set 200 years before the events of Game of Thrones.",
    isTopRated: true,
    hasHDContent: true,
  },
  {
    id: 5,
    title: "The Bear",
    type: "TV Series",
    releaseYear: 2022,
    poster: {
      src: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQfFdxGEWCT0J0LT-o-fO7fw2QgfZ41Bwwdhidpwht4CCZ6NJOC",
      alt: "The Bear Poster",
    },
    rating: {
      imdb: 8.7,
      rottenTomatoes: 99,
    },
    genre: ["Comedy", "Drama"],
    creator: "Christopher Storer",
    mainCast: ["Jeremy Allen White", "Ebon Moss-Bachrach", "Ayo Edebiri"],
    seasons: 2,
    episodes: 18,
    streamingOn: ["Hulu", "FX"],
    awards: ["2 Golden Globe Awards", "Emmy Award", "Critics Choice Award"],
    description:
      "A young chef from the fine dining world returns to Chicago to run his family's sandwich shop after the death of his brother.",
    isTopRated: true,
    hasHDContent: true,
  },
];
